### ISSUE TITLE
Dunno how to execute

### ISSUE THREAD

**Issue by JustAB0x** [Bluscream/ISPValidator#1]
I used the ts3 plugin file and the validator does not pop up in my pyTSon list.

**Comment by Bluscream** [comment]
You need to check "Accept different API versions"

**Comment by JustAB0x** [comment]
Done that.

**Comment by JustAB0x** [comment]
Does not help

**Comment by Bluscream** [comment]
Check your client log [CTRL] + [L]

**Comment by JustAB0x** [comment]
https://i.imgur.com/uWzjkZj.png

**Comment by JustAB0x** [comment]
You can reply in german btw

**Comment by Bluscream** [comment]
You need https://raw.githubusercontent.com/Bluscream/pyTSon_plugins/master/include/getvalues.py in `%appdata%\TS3Client\plugins\pyTSon\include\getValues.py`

**Comment by JustAB0x** [comment]
Tried it, doesnt work.

**Comment by Bluscream** [comment]
error?

**Comment by JustAB0x** [comment]
Its the same

**Comment by Bluscream** [comment]
ups das muss getvalues.py heissen

**Comment by JustAB0x** [comment]
hab ich bereits so probiert. Hab dein ganzes pack runtergladen :P

**Comment by JustAB0x** [comment]
bzw alles was interessant war + includes

**Comment by Bluscream** [comment]
was sagt die konsole?

**Comment by JustAB0x** [comment]
meinste die pyTSon konsole?

**Comment by Bluscream** [comment]
ne die ts log console

**Comment by JustAB0x** [comment]
meinste den client log? sorry das ich mich grad so dumm anstelle^^

**Comment by Bluscream** [comment]
joa

**Comment by Bluscream** [comment]
am besten die zeilen rauskopieren und hier einfügen geht schneller alsn screenshot

**Comment by Fytcher** [comment]
Traceback (most recent call last):  
File "C:/Users/poolc/AppData/Roaming/TS3Client/plugins/pyTSon/include\pytsonui\console.py", line 351, in runCommand 
res = eval(cmd, self.globals) 
File "<string>", line 1, in <module> 
File "<string>", line 2, in <module>
 ImportError: cannot import name 'getValues'

**Comment by JustAB0x** [comment]
```
2017-11-19 00:10:47.874487|ERROR   |pyTSon.PluginHost.reload|   |Error loading python plugin from C:/Users/user/AppData/Roaming/TS3Client/plugins/pyTSon\scripts\ISPValidator\: Traceback (most recent call last):
                                                                   File "C:/Users/user/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\pluginhost.py", line 321, in reload
                                                                     cls.modules[base] = importlib.__import__(base)
                                                                   File "<frozen importlib._bootstrap>", line 1055, in __import__
                                                                   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
                                                                   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
                                                                   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
                                                                   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
                                                                   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
                                                                   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
                                                                   File "C:/Users/user/AppData/Roaming/TS3Client/plugins/pyTSon/scripts\ISPValidator.py", line 2, in <module>
                                                                     from pytsonui import setupUi, getValues, ValueType
                                                                 ImportError: cannot import name 'getValues'
```

**Comment by JustAB0x** [comment]
bitte^^

**Comment by Bluscream** [comment]
hmm hast du die aktuelly nightly von pytson? https://repo.4qt.de/pyTSon/nightlies/latest/

**Comment by JustAB0x** [comment]
ne, werde ich mal schnell drauf packen

**Comment by JustAB0x** [comment]
immer noch das selbe problem

**Comment by JustAB0x** [comment]
Habe bei den import setupUi, getValues, ValueType gegen * usgetauscht als test, danach wird mir im log angezeigt: ImportError: No module named 'ts3'

**Comment by JustAB0x** [comment]
so, getvalues konnte ich jetzt manuall über `import getvalues` beheben. Jetzt habe ich das Problem dass `ts3.getPluginPath()` nicht erkannt wird

**Comment by Bluscream** [comment]
Hmm probier mal die version von https://github.com/Bluscream/pyTSon_plugins/

**Comment by JustAB0x** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\blusc\\AppData\\Roaming\\TS3Client\\plugins\\pyTSon\\scripts\\ISPValidator\\isps.txt'`

**Comment by JustAB0x** [comment]
der nimmt wohl deinen pfad ;D

**Comment by JustAB0x** [comment]
konnte die andere version durch das hinzufügen von `import ts3lib as ts3` zum selben error "bringen"

**Comment by Bluscream** [comment]
Hmm. Bist du grad auf ts irgendwo?

**Comment by JustAB0x** [comment]
auf meinem eigenen, ja.

**Comment by Bluscream** [comment]
Soll ich da mal draufkommen und dir helfen?

**Comment by Fytcher** [comment]
x-treme.ts3index.com

**Comment by Bluscream** [comment]
Done
